### ISSUE TITLE
QQbot出现频繁上下线的情况，并伴有报错

### ISSUE THREAD

**Issue by ldcivan** [Zokhoi/LilyWhiteBot#4]
出现报错：
- [下线通知]该帐号密码目前已经泄露，请前往https://accounts.qq.com/007进行查询。

但实际上账号并没有被冻结。

**Comment by ldcivan** [comment]
另，VPN全局开启，检查过token的情况下下出现
[ERROR] [bridge.js] <BotSend> Rejected:  request to https://api.telegram.org/bot2094987225:AAFTnScCnz_Ewe-zFhU_nk8xn_aCZ8eiCBM/sendMessage failed, reason: connect ETIMEDOUT 103.200.31.172:443
FetchError: request to https://api.telegram.org/bot2094987225:AAFTnScCnz_Ewe-zFhU_nk8xn_aCZ8eiCBM/sendMessage failed, reason: connect ETIMEDOUT 103.200.31.172:443
    at ClientRequest.<anonymous> (C:\Users\86178\Desktop\LilyWhiteBot-master\node_modules\node-fetch\lib\index.js:1461:11)
    at ClientRequest.emit (events.js:400:28)
    at TLSSocket.socketErrorListener (_http_client.js:475:9)
    at TLSSocket.emit (events.js:400:28)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
